name: Full Deploy to EC2 (zero manual setup)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH (auto bootstrap server)
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "=== SYSTEM UPDATE ==="
            sudo apt-get update -y

            echo "=== INSTALL REQUIRED PACKAGES ==="
            sudo apt-get install -y git curl unzip

            echo "=== INSTALL DOCKER (if missing) ==="
            if ! command -v docker &> /dev/null
            then
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker $USER
            fi

            echo "=== ENABLE DOCKER ==="
            sudo systemctl enable docker
            sudo systemctl start docker

            echo "=== INSTALL DOCKER COMPOSE (plugin) ==="
            if ! docker compose version &> /dev/null
            then
              sudo apt-get install -y docker-compose-plugin
            fi

            echo "=== INSTALL AWS CLI (if missing) ==="
            if ! command -v aws &> /dev/null
            then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -o awscliv2.zip
              sudo ./aws/install
            fi

            echo "=== SET APP DIR ==="
            APP_DIR=/opt/yaml-validator

            echo "=== CREATE APP DIR ==="
            sudo mkdir -p $APP_DIR
            sudo chown -R $USER:$USER $APP_DIR
            
            echo "=== CLONE / UPDATE REPO ==="
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/PatvakanGasparyan/yaml---terraform-final-checker.git $APP_DIR
            else
              cd $APP_DIR
              git fetch origin
              git reset --hard origin/main
            fi
            
            cd $APP_DIR

            echo "=== UPDATE CODE ==="
            git fetch origin
            git reset --hard origin/main

            echo "=== CONFIG AWS ENV ==="
            export AWS_ACCESS_KEY_ID=${{ secrets.IAM_ACCESS_KEY }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.IAM_SECRET_KEY }}
            export AWS_DEFAULT_REGION=eu-north-1

            echo "=== DOWNLOAD .ENV FROM S3 ==="
            aws s3 cp s3://validator.bucket/.env .env

            echo "=== STOP OLD CONTAINERS ==="
            docker compose down || true

            echo "=== BUILD AND START ==="
            docker compose up -d --build

            echo "=== DONE ==="
